[build]
  command = "npx expo export --platform web --output-dir web-build"
  publish = "web-build"

[[redirects]]
  from = "/Accueil"
  to = "/home"
  status = 301

[[redirects]]
  from = "/CalculPertesDeCharge"
  to = "/calcul-pertes-de-charge"
  status = 301

[[redirects]]
  from = "/CalculEtablissement"
  to = "/calcul-etablissement"
  status = 301

[[redirects]]
  from = "/DebitMaxPEI"
  to = "/capacite-pei"
  status = 301

[[redirects]]
  from = "/Relais"
  to = "/pompage-relais"
  status = 301

[[redirects]]
  from = "/GrandsFeux"
  to = "/liquides-inflammables"
  status = 301

[[redirects]]
  from = "/Parametres"
  to = "/reglages"
  status = 301

[[redirects]]
  from = "/ValeursPerso"
  to = "/valeurs-perso"
  status = 301

[[redirects]]
  from = "/accueil"
  to = "/home"
  status = 301

[[redirects]]
  from = "/calculpertesdecharge"
  to = "/calcul-pertes-de-charge"
  status = 301

[[redirects]]
  from = "/calculetablissement"
  to = "/calcul-etablissement"
  status = 301

[[redirects]]
  from = "/debitmaxpei"
  to = "/capacite-pei"
  status = 301

[[redirects]]
  from = "/relais"
  to = "/pompage-relais"
  status = 301

[[redirects]]
  from = "/grandsfeux"
  to = "/liquides-inflammables"
  status = 301

[[redirects]]
  from = "/parametres"
  to = "/reglages"
  status = 301

[[redirects]]
  from = "/valeursperso"
  to = "/valeurs-perso"
  status = 301

[[redirects]]
  from = "/support"
  to = "/support.html"
  status = 200

[[redirects]]
  from = "/support/"
  to = "/support.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy-policy.html"
  status = 200
